[package]
name = "annoyancube"
version = "0.1.0"
edition = "2025"
[dependencies]
bevy = "0.17" # make sure this is the latest version
[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3